diff --git a/4.0/Dockerfile b/4.0/Dockerfile
index d9afd19..6e8456d 100644
--- a/4.0/Dockerfile
+++ b/4.0/Dockerfile
@@ -62 +62 @@ RUN set -ex; \
-	make -C /usr/src/redis -j "$(nproc)"; \
+	make CFLAGS="-static" EXEEXT="-static" LDFLAGS="-I/usr/local/include/" -C /usr/src/redis -j "$(nproc)"; \
